### ISSUE TITLE
can't transfer CODEX savegame to Steam

### ISSUE THREAD

**Issue by thekjohn** [GoobyCorp/DOOMSaveManager#3]
I used CODEX release and played a few hours then I bought the game on Steam, hoping your tool can transfer the save game and I don't have to replay my progression.

I get this error message after Bethesda.net login:
"There was an error loading your game"

Transfer tool settings:
https://imgur.com/pAzrmrs

**Comment by thekjohn** [comment]
I deleted everything in Steam\UserData\xx\xx\remote, but no luck. Now I don't even get an error message in the game, but I see 3 unused slots instead.

**Comment by thekjohn** [comment]
WTF...

1) I created "c:\Users\xxx\Saved Games\id Software\DOOMEternal\base\savegame\savegame.unencrypted" (otherwise the tool shows an error message)
2) I transferred codex to savegame.unencrypted
3) I transferred savegame.unencrypted to steam
4) I got the errors I posted above

5) (I cried a bit)

6) restarted my PC
7) everything is fine !!!!!!!!

Thank you man, you saved me lot of time!

Have a nice day!

**Comment by stevethers** [comment]
Can you help me out?

**Comment by conkerts** [comment]
Hmm, I'm in a similar situation.
Finally bought the game, but it doesn't accept my old savegame. That's really annoying
I did exactly that:
2 I transferred codex to savegame.unencrypted
3 I transferred savegame.unencrypted to steam
4 I got the errors I posted above

I'm really interested how your steps 4 and 5 worked so that the game finally accepted your savegame.

For me it looks like the Profile is also only 100KB while the profile from a newly started game is already 400KB ...
